### ISSUE TITLE
Feature/Sliders for UI sounds

### ISSUE THREAD

**Issue by Kaiji-Kun** [4rg0n/songs-of-syx-mod-more-options#15]
Thanks for this great mod!

Hoping you can add sliders for the grating UI sounds on click and mouseover.

**Comment by 4rg0n** [comment]
Noted =D

**Comment by 4rg0n** [comment]
Lol... fun story: As I was looking where I can access the UI sounds, I found a way of the game to set the gain for specific "types" of sounds like "MUSIC". There also was this type "EFFECT" and the classes involved in the UI sounds are called "SoundEffect". So I went into the in game options and there it was: "Volume-Effects":  

![image](https://github.com/user-attachments/assets/8f24791f-a878-41a6-a558-dd62259da106)

This does exactly what you want (case closed) ^^
