### ISSUE TITLE
I cant see the menu.

### ISSUE THREAD

**Issue by papoycore** [4rg0n/songs-of-syx-mod-more-options#5]
The menu size is too big for me( i play this game on laptop and my screen resolution is 1366x768. thank you..

![Screenshot (8)](https://github.com/4rg0n/songs-of-syx-mod-more-options/assets/72886370/39917b48-902c-445e-ae3d-aa3db7eb5580)

**Comment by 4rg0n** [comment]
Hayo, thanks for mentioning this. I squeezed some pixels out of the height in the current branch I'm developing.
Will be ready in a few days. For the future some kind of scaling depending on the screen resolution would be nice =D

**Comment by 4rg0n** [comment]
![image](https://github.com/4rg0n/songs-of-syx-mod-more-options/assets/5048544/af5f9a5f-1234-43f3-adf8-56d0b8779b9c)

Got it down to 716px. I'll do some testing and a release of version 1.6.0 today I guess.  
For newer versions the ui will use the full screen instead of a window.

**Comment by 4rg0n** [comment]
The ui is now somewhat scalable in height depending on screen size since version 1.7
